<?php

namespace Database\Seeders;

use App\Models\PlanAutopool;
use App\Models\PlanDirect;
use App\Models\PlanLevel;
use App\Models\PlanMonth;
use App\Models\PlanReward;
use Carbon\Carbon; 
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlanSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


         $now = Carbon::now();

        $commissions = [
            ['level' => 0, 'mobile' => 2.00, 'dth' => 2.00, 'bbps' => 2.00, 'gas' => 2.00, 'water' => 2.00, 'insurance' => 2.00, 'loan' => 2.00, 'status' => 1, 'type' => 'free'],
            ['level' => 1, 'mobile' => 0.40, 'dth' => 0.40, 'bbps' => 0.25, 'gas' => 0.25, 'water' => 0.25, 'insurance' => 5.00, 'loan' => 5.00, 'status' => 1, 'type' => 'free'],
            ['level' => 2, 'mobile' => 0.30, 'dth' => 0.30, 'bbps' => 0.20, 'gas' => 0.20, 'water' => 0.20, 'insurance' => 4.00, 'loan' => 4.00, 'status' => 1, 'type' => 'free'],
            ['level' => 3, 'mobile' => 0.20, 'dth' => 0.20, 'bbps' => 0.15, 'gas' => 0.15, 'water' => 0.15, 'insurance' => 3.00, 'loan' => 3.00, 'status' => 1, 'type' => 'free'],
            ['level' => 4, 'mobile' => 0.10, 'dth' => 0.10, 'bbps' => 0.10, 'gas' => 0.10, 'water' => 0.10, 'insurance' => 2.00, 'loan' => 2.00, 'status' => 1, 'type' => 'free'],
            ['level' => 5, 'mobile' => 0.03, 'dth' => 0.03, 'bbps' => 0.02, 'gas' => 0.02, 'water' => 0.02, 'insurance' => 0.25, 'loan' => 0.25, 'status' => 1, 'type' => 'free'],

            ['level' => 0, 'mobile' => 3.00, 'dth' => 3.00, 'bbps' => 0.30, 'gas' => 0.30, 'water' => 0.30, 'insurance' => 10.00, 'loan' => 10.00, 'status' => 1, 'type' => 'paid'],
            ['level' => 1, 'mobile' => 0.40, 'dth' => 0.40, 'bbps' => 0.15, 'gas' => 0.15, 'water' => 0.15, 'insurance' => 5.00, 'loan' => 5.00, 'status' => 1, 'type' => 'paid'],
            ['level' => 2, 'mobile' => 0.30, 'dth' => 0.30, 'bbps' => 0.10, 'gas' => 0.10, 'water' => 0.10, 'insurance' => 4.00, 'loan' => 4.00, 'status' => 1, 'type' => 'paid'],
            ['level' => 3, 'mobile' => 0.20, 'dth' => 0.20, 'bbps' => 0.05, 'gas' => 0.05, 'water' => 0.05, 'insurance' => 3.00, 'loan' => 3.00, 'status' => 1, 'type' => 'paid'],
            ['level' => 4, 'mobile' => 0.10, 'dth' => 0.10, 'bbps' => 0.03, 'gas' => 0.03, 'water' => 0.03, 'insurance' => 2.00, 'loan' => 2.00, 'status' => 1, 'type' => 'paid'],
            ['level' => 5, 'mobile' => 0.03, 'dth' => 0.03, 'bbps' => 0.02, 'gas' => 0.02, 'water' => 0.02, 'insurance' => 0.50, 'loan' => 0.50, 'status' => 1, 'type' => 'paid'],
        ];

        foreach ($commissions as &$commission) {
            $commission['created_at'] = $now;
            $commission['updated_at'] = $now;
        }

        DB::table('plan_recharge_commisions')->insert($commissions);
    

 
        PlanReward::insert([
            [
                'direct_required' => 15, 
                'generation_team_required' => 0, 
                'tour' => "",
                'direct_business_required' => 0,
                'generation_business_required' => 0,
                'name' => "15 DIRECT",
                'rank' => 'BRONZE',
                'reward' => 'WELCOME KIT',
                'value' => 1,
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'generation_team_required' => 30, 
                'tour' => "NATIONAL TRIP",
                'direct_business_required' => 0,
                'generation_business_required' => 0,
                'name' => "4 BRONZE + 30 TEAM",
                'reward' => 'SMART PHONE',
                'value' => 1.5,
                'rank' => 'SILVER',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'generation_team_required' => 150, 
                'tour' => "GOA TRIP",
                'direct_business_required' => 0,
                'generation_business_required' => 0,
                'name' => "4 SILVER + 150 TEAM",
                 'rank' => 'GOLD',
                 'value' => 1.75,
                'reward' => 'LAPTOP',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'generation_team_required' => 750, 
                'tour' => "THAILAND",
                 'rank' => 'PLATINUM',
                'direct_business_required' => 0,
                'generation_business_required' => 0,
                'name' => "4 GOLD + 750 TEAM",
                'reward' => 'BIKE',
                'value' => 2,
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
            [
                'direct_required' => 0, 
                'generation_team_required' => 3750, 
                'tour' => "DUBAI",
                 'rank' => 'TOPAZ',
                'direct_business_required' => 0,
                'generation_business_required' => 0,
                'name' => "4 PLATINUM + 3750",
                'reward' => 'CAR',
                'value' => 1.75,
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
            [
                'direct_required' => 0, 
                'generation_team_required' => 18750, 
                'tour' => "YEARLY 1 - FOREIGN TRIP WITH FAMILY",
                 'rank' => 'RUBY',
                'direct_business_required' => 0,
                'generation_business_required' => 0,
                'name' => "4 TOPAZ + 18750",
                'value' => 1.5,
                'reward' => 'LUXURY CAR',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'generation_team_required' => 93750, 
                'tour' => "YEARLY 2 - FOREIGN TRIP WITH FAMILY",
                 'rank' => 'DIAMOND',
                'direct_business_required' => 0,
                'generation_business_required' => 0,
                'name' => "4 RUBY + 93750",
                'reward' => 'LUXURY HOUSE',
                 'value' => 1,
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
    ]);


    PlanAutopool::insert([
            [
                'direct_required' => 2,
                'level' => 1,
                'source' => 'autopool',
                'commision_type' => 'fix',
                'value' => 10,
                'status' => 1,
                'wallet_type_id' => 1,
                'created_at' => '2025-06-04 11:00:20',
                'updated_at' => '2025-06-04 11:00:20',
            ],
            [
                'direct_required' => 4,
                'level' => 2,
                'source' => 'autopool',
                'commision_type' => 'fix',
                'value' => 20,
                'status' => 1,
                'wallet_type_id' => 1,
                'created_at' => '2025-06-04 11:00:20',
                'updated_at' => '2025-06-04 11:00:20',
            ],
            [
                'direct_required' => 8,
                'level' => 3,
                'source' => 'autopool',
                'commision_type' => 'fix',
                'value' => 60,
                'status' => 1,
                'wallet_type_id' => 1,
                'created_at' => '2025-06-04 11:00:20',
                'updated_at' => '2025-06-04 11:00:20',
            ],
            [
                'direct_required' => 16,
                'level' => 4,
                'source' => 'autopool',
                'commision_type' => 'fix',
                'value' => 600,
                'status' => 1,
                'wallet_type_id' => 1,
                'created_at' => '2025-06-04 11:00:20',
                'updated_at' => '2025-06-04 11:00:20',
            ],
            [
                'direct_required' => 32,
                'level' => 5,
                'source' => 'autopool',
                'commision_type' => 'fix',
                'value' => 17000,
                'status' => 1,
                'wallet_type_id' => 1,
                'created_at' => '2025-06-04 11:00:20',
                'updated_at' => '2025-06-04 11:00:20',
            ],
            [
                'direct_required' => 64,
                'level' => 6,
                'source' => 'autopool',
                'commision_type' => 'fix',
                'value' => 160000,
                'status' => 1,
                'wallet_type_id' => 1,
                'created_at' => '2025-06-04 11:00:20',
                'updated_at' => '2025-06-04 11:00:20',
            ],
            [
                'direct_required' => 128,
                'level' => 7,
                'source' => 'autopool',
                'commision_type' => 'fix',
                'value' => 102400000,
                'status' => 1,
                'wallet_type_id' => 1,
                'created_at' => '2025-06-04 11:00:20',
                'updated_at' => '2025-06-04 11:00:20',
            ],
        ]);

        PlanMonth::insert([
            [
                'direct_required' => 15, 
                'generation_team_required' => 0, 
                'name' => "15 DIRECT", 
                'rank' => 'BRONZE',
                'total_reward' => 450,
                'month' => 3,
                'value' => 150,
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'generation_team_required' => 30,  
                'name' => "4 BRONZE + 30 TEAM",
                'total_reward' => 1800,
                'value' => 300,
                'month' => 6,
                'rank' => 'SILVER',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'generation_team_required' => 150,  
                'name' => "4 SILVER + 150 TEAM",
                'total_reward' => 18000,
                'value' => 1500,
                'month' => 12,
                'rank' => 'GOLD',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'generation_team_required' => 750, 
                'name' => "4 GOLD + 750 TEAM",
                'total_reward' => 270000,
                'value' => 7500,
                'month' => 36,
                'rank' => 'PLATINUM',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
            [
                'direct_required' => 0, 
                'generation_team_required' => 3750, 
                'name' => "4 PLATINUM + 3750",
                'total_reward' => 1800000,
                'value' => 37500,
                'month' => 48,
                'rank' => 'TOPAZ',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
            [
                'direct_required' => 0, 
                'generation_team_required' => 18750, 
                'name' => "4 TOPAZ + 18750",
                'total_reward' => 11250000,
                'value' => 187500,
                'month' => 60,
                'rank' => 'RUBY',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'generation_team_required' => 93750, 
                'name' => "4 RUBY + 93750",
                'total_reward' => 67500000,
                'value' => 937500,
                'month' => 72,
                'rank' => 'DIAMOND',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
    ]);
         
      PlanDirect::insert([
            [
                'direct_required' => 0, 
                'level' => '1',
                'source' => "direct",
                'commision_type' => "fixed",
                'type' => "prime",
                'value' => '200',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '1',
                'source' => "direct",
                'commision_type' => "fixed",
                'type' => "super",
                'value' => '500',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ]
    ]);
      PlanLevel::insert([
            [
                'direct_required' => 0, 
                'level' => '1',
                'source' => "direct",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '40',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '2',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '8',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '3',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '4',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '4',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '2',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '5',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '6',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '7',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '8',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '9',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '10',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '11',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '12',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '13',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '14',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '15',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '16',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '17',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '18',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '19',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '20',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '21',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '22',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '23',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '24',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '25',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '1',
                'source' => "direct",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '50',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '2',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '10',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '3',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '5',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '4',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '2.5',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '5',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '6',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '7',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '8',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '9',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '10',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '11',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '12',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '13',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '14',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '15',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '16',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '17',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '18',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '19',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '20',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '1',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '21',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '0.5',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '22',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '0.5',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '23',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '0.5',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '24',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '0.5',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'direct_required' => 0, 
                'level' => '25',
                'source' => "level",
                'commision_type' => "percent",
                'type' => "super_prime",
                'value' => '0.5',
                'status' => '1',
                'wallet_type_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
    ]);

    }
}
